"""Services for simulation routes.

This submodule defines the service functions for simulation routes.

Functions:
    run_sim(payload):
        Run a simulation using the specified configuration.
"""

from emergency_response.app import emergency_response_sim as core_run
from backend.schemas.sim import SimInput, SimOutput
from utils.config_validator import load_cfg


def run_sim(payload: SimInput) -> SimOutput:
    """Run a simulation using the specified configuration.

    This function loads the configuration specified in 'payload', executes
    the core simulation, and returns the results as a 'SimOutput' object.
    The output includes paths to the incident report, apparatus events,
    and step trace files generated by the simulation.

    Args:
        payload (SimInput): The simulation input containing the configuration
            directory and configuration name.

    Returns:
        SimOutput: An object containing the paths to the simulation output
            files:
            - 'path_incident_report': Path to the incident report file.
            - 'path_apparatus_events': Path to the apparatus events file.
            - 'path_step_trace': Path to the step trace file.
    """
    cfg = load_cfg(payload.config_dir, payload.config_name)
    path_incident_report, path_apparatus_events, path_step_trace = core_run(cfg)
    result = SimOutput(
        path_incident_report = path_incident_report,
        path_apparatus_events = path_apparatus_events,
        path_step_trace = path_step_trace
    )
    return result
